/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 satellite.gltf --transform 
Files: satellite.gltf [50.24MB] > satellite-transformed.glb [386.47KB] (99%)
Author: Daan van Leeuwen (https://sketchfab.com/superwortel)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/satellite-d232fe608c874009bad9613c8093a972
Title: Satellite
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import { easing } from 'maath'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/satellite-transformed.glb')
  const groupRef = useRef()

  useFrame((state, delta) => {
    easing.dampE(groupRef.current.rotation, [state.pointer.y*2, -state.pointer.x*2, 0], 1, delta)
  })

  return (
    <group {...props} dispose={null} ref={groupRef}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.lambert1} scale={-0.04} position={[0,0,1.5]} rotation={[-Math.PI / 2, 0, 0]}/>
      <ambientLight intensity={10} color={"#c4c4c4"}/>
    </group>
  )
}

useGLTF.preload('/satellite-transformed.glb')
